name: Read Chuck Norris Joke
description: Calls the Chuck Norris Joke API and Returns the Joke
inputs:
  url:
    description: API URL to read a Chuck Norris joke from - set this externally at repo level.
    required: true

outputs:
  cn_joke:
    description: Chuck Norris Joke
    value: ${{ steps.cn_joke.outputs.cn_joke }}

runs:
  using: 'composite'
  steps:
    - name: Read Chuck Norris joke
      id: cn_joke
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        read_cn_joke.py

    - name: debug simple python
      id: cn_debug
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        python simple_test.py
